[general]
dylib_map = dylib_map.conf
address_hooks = address-hooks.conf
patches = patches.conf
entry_override = 0x100005088
entry_expected = ff8301d1f65703a9f44f04a9fd7b05a9
entry_prepare_lib = ./libsword3_host.so
entry_prepare_symbol = sword3_host_prepare
