[general]
dylib_map = dylib_map.conf
address_hooks = address-hooks.conf
entry_override = 0x10002c3b0
entry_expected = ff0302d1f65705a9f44f06a9fd7b07a9
entry_prepare_lib = ./libsword3_host.so
entry_prepare_symbol = sword3_host_prepare
