#!/usr/bin/env python3
"""Rasterize the host-menu CJK labels into an embedded PNG header."""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src/ports/sword3/host_menu_atlas.h"
FONT = Path("/usr/share/fonts/truetype/droid/DroidSansFallbackFull.ttf")

LABELS = [
    ("item", "物品", 28),
    ("equip", "装备", 28),
    ("skill", "奇术", 28),
    ("status", "状态", 28),
    ("book", "天书", 28),
    ("save", "存盘", 28),
    ("load", "读取", 28),
    ("log", "记载", 28),
    ("opt", "设置", 28),
    ("leave", "离开", 28),
    ("title", "系统菜单", 32),
    ("hint_data", "数据稍后从游戏内存读取", 22),
    ("hint_ab", "A 确认   B 返回", 20),
    ("stub_save", "存盘（尚未接入）", 24),
    ("stub_load", "读取（尚未接入）", 24),
    ("stub_log", "记载（尚未接入）", 24),
    ("stub_opt", "设置（尚未接入）", 24),
    ("pick_save", "选择存档", 24),
    ("pick_load", "选择读档", 24),
    ("slot", "档位", 22),
    ("empty", "空", 22),
    ("used", "已存", 22),
    ("d0", "0", 22),
    ("d1", "1", 22),
    ("d2", "2", 22),
    ("d3", "3", 22),
    ("d4", "4", 22),
    ("d5", "5", 22),
    ("d6", "6", 22),
    ("d7", "7", 22),
    ("d8", "8", 22),
    ("d9", "9", 22),
]


def main() -> None:
    cells = []
    images = []
    pad = 8
    for name, text, size in LABELS:
        font = ImageFont.truetype(str(FONT), size)
        dummy = Image.new("RGBA", (8, 8), (0, 0, 0, 0))
        draw = ImageDraw.Draw(dummy)
        box = draw.textbbox((0, 0), text, font=font)
        w = box[2] - box[0] + pad * 2
        h = box[3] - box[1] + pad * 2
        img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
        ImageDraw.Draw(img).text(
            (pad - box[0], pad - box[1]),
            text,
            font=font,
            fill=(255, 236, 196, 255),
        )
        images.append((name, img))

    width = max(img.width for _, img in images)
    height = sum(img.height for _, img in images)
    atlas = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    y = 0
    for name, img in images:
        atlas.paste(img, (0, y))
        cells.append((name, 0, y, img.width, img.height))
        y += img.height

    from io import BytesIO

    buf = BytesIO()
    atlas.save(buf, format="PNG", optimize=True)
    data = buf.getvalue()

    lines = [
        "/* Generated by scripts/gen_host_menu_atlas.py — do not edit. */",
        "#ifndef SWORD3_HOST_MENU_ATLAS_H",
        "#define SWORD3_HOST_MENU_ATLAS_H",
        "",
        "enum host_menu_label {",
    ]
    for i, (name, _, _, _, _) in enumerate(cells):
        ident = name.upper()
        lines.append(f"\tHOST_MENU_LBL_{ident} = {i},")
    lines.append("\tHOST_MENU_LBL_COUNT")
    lines.append("};")
    lines.append("")
    lines.append("struct host_menu_glyph {")
    lines.append("\tint x;")
    lines.append("\tint y;")
    lines.append("\tint w;")
    lines.append("\tint h;")
    lines.append("};")
    lines.append("")
    lines.append("static const struct host_menu_glyph host_menu_lbl[] = {")
    for name, x, gy, w, h in cells:
        lines.append(f"\t{{ {x}, {gy}, {w}, {h} }}, /* {name} */")
    lines.append("};")
    lines.append("")
    lines.append(f"static const unsigned host_menu_atlas_png_len = {len(data)};")
    lines.append("static const unsigned char host_menu_atlas_png[] = {")
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 16])
        lines.append(f"\t{chunk},")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(data)} png bytes, {atlas.size[0]}x{atlas.size[1]})")


if __name__ == "__main__":
    main()
