set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(ROCKNIX_TOOLCHAIN_ROOT
    "/home/ubuntu/distribution/build.ROCKNIX-RK3326.aarch64/toolchain"
    CACHE PATH "ROCKNIX RK3326 toolchain root")

set(CMAKE_C_COMPILER
    "${ROCKNIX_TOOLCHAIN_ROOT}/bin/aarch64-rocknix-linux-gnu-gcc")
set(CMAKE_CXX_COMPILER
    "${ROCKNIX_TOOLCHAIN_ROOT}/bin/aarch64-rocknix-linux-gnu-g++")
set(CMAKE_SYSROOT
    "${ROCKNIX_TOOLCHAIN_ROOT}/aarch64-rocknix-linux-gnu/sysroot")

set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(ENV{PKG_CONFIG_SYSROOT_DIR} "${CMAKE_SYSROOT}")
set(ENV{PKG_CONFIG_LIBDIR}
    "${CMAKE_SYSROOT}/usr/lib/pkgconfig:${CMAKE_SYSROOT}/usr/share/pkgconfig")
